cleanup and 'beautification'
- added LSB headers to init-scripts
- more consistent acronym display across browsers, incorporate cursor:help
  into acronyms (avoids <span> elements)
- progress bars with gradient colouring
- avoid umask in xmlqstat-cacher.pl

diff --git a/scripts/init-scripts/cocoon b/scripts/init-scripts/cocoon
--- a/scripts/init-scripts/cocoon
+++ b/scripts/init-scripts/cocoon
@@ -1,51 +1,69 @@
 #!/bin/sh
-#
 # Simple start script for the Cocoon server engine
+#
+# 0. Define safe path
+PATH=/bin:/usr/bin
 #
 ## CUSTOMIZE AS REQUIRED
 #
-# require GridEngine information for later queries
-# (only required when using the command-generator)
-: ${SGE_ROOT:=/opt/grid}
-: ${SGE_CELL:=default}
+# 1. Downgrade to a non-root user account (adjust as required)
+runAs=cfdadmin
 
-JAVA_HOME=/usr/lib/jvm/java
+# 2. Location of cocoon server and java
 COCOON_HOME=/data/app/cocoon
+JAVA_HOME=/usr/lib/jvm/java
 
-export SGE_ROOT SGE_CELL JAVA_HOME COCOON_HOME
+# 3. Might require GridEngine information for later queries
+#    (only required when using the command-generator)
+SGE_ROOT=/opt/grid
+SGE_CELL=default
 
-## Init the Grid Engine path/environment variables
-## so our script can access Grid Engine commands
+# 4. Extra path(s) for anything we wish to use via the java CommandGenerator
+for d in /data/app/bin
+do
+    [ -d $d ] && PATH=$PATH:$d
+done
+
+export COCOON_HOME JAVA_HOME PATH
+unset DISPLAY  # safety
+
+#---------------------------------------------------------------------------
+# The following lines provide the necessary info for adding a startup script
+# according to the Linux Standard Base Specification (LSB).
+#
+### BEGIN INIT INFO
+# Provides:       xmlqstat.cocoon
+# Required-Start: $network $remote_fs
+# Should-Start:   network-remotefs
+# Required-Stop:
+# Default-Start:  3 5
+# Default-Stop: 0 1 2 6
+# Description:  start cocoon for xmlqstat
+### END INIT INFO
+#---------------------------------------------------------------------------
+
+# this script should run as 'runAs'
+if [ "$UID" -eq 0 -a "${runAs:=root}" != root ]
+then
+    exec sudo -S -u $runAs $0 $@
+    exitcode=$?       # retain exitcode
+
+    [ "$exitcode" == 0 ] || {
+        echo "could not change to $runAs"
+        exit $exitcode
+    }
+fi
+
+# Init GridEngine path/environment variables
+# to allow webserver access to GridEngine commands
 if [ -f $SGE_ROOT/$SGE_CELL/common/settings.sh ]
 then
+    export SGE_ROOT SGE_CELL
     . $SGE_ROOT/$SGE_CELL/common/settings.sh
 else
     unset SGE_ROOT SGE_CELL
 fi
 
-# extra path for anything we wish to use via the java CommandGenerator
-PATH=$PATH:/data/app/bin
-
-unset DISPLAY  # a bit extra safety
-
-##
-## System start scripts typically run as root user,
-## downgrade to a non-root user account. Adjust as required
-##
-runas_user=cfdadmin
-# -------------------------------------------------------------------------
-# this script should run as 'runas_user'
-#
-if [ "$UID" -eq 0 -a "${runas_user:=root}" != root ]
-then
-    exec sudo -S -u $runas_user $0 $@
-    exitcode=$?       # retain exitcode
-
-    [ "$exitcode" == 0 ] || {
-       echo "could not change to $runas_user"
-       exit $exitcode
-    }
-fi
 
 daemon=$COCOON_HOME/cocoon.sh
 name=cocoon
@@ -70,13 +88,14 @@ start)
     ;;
 
 stop)
-    echo "Stopping $desc: $name"
+    echo -n "Stopping $desc: "
     # get pid
-    pid=`ps -f -C java | awk '{if (/cocoon/) print $2}'`
+    pid=`ps aux | awk '{if (/java/ && /cocoon/ && !/awk/) print $2}'`
     if [ -z "$pid" ]
     then
         echo "process not found"
     else
+        echo "sending TERM signal"
         kill -15 $pid
     fi
     ;;
@@ -92,5 +111,6 @@ restart)
     exit 1
     ;;
 esac
+
 exit 0
-# ------------------------------------------------------------- end-of-file
+# -------------------------------------------------------------- end-of-file
diff --git a/scripts/init-scripts/httpi b/scripts/init-scripts/httpi
--- a/scripts/init-scripts/httpi
+++ b/scripts/init-scripts/httpi
@@ -1,40 +1,51 @@
 #!/bin/sh
-#
 # Simple start script for the httpi web-server
+
+# 0. Define safe path
+PATH=/bin:/usr/bin
 #
 ## CUSTOMIZE AS REQUIRED
 #
-# maybe require GridEngine information for later queries
-: ${SGE_ROOT:=/opt/grid}
+# 1. Downgrade to a non-root user account (adjust as required)
+runAs=nobody
 
+# 2. Location of httpi server
 HTTPI_HOME=/data/app/httpi
-PATH=/bin:/usr/bin:$SGE_ROOT/bin/`$SGE_ROOT/util/arch`
 
-# extra path for anything we wish to but don't want to add to the
-# cgi scripts ourselves
-PATH=$PATH:/data/app/bin
+# 3. Extra path(s) for anything we wish to have but don't want to add to the
+#    cgi scripts ourselves
+for d in /data/app/bin
+do
+    [ -d $d ] && PATH=$PATH:$d
+done
 
-export SGE_ROOT PATH
-unset DISPLAY   # a bit extra safety
+export PATH
+unset SGE_ROOT DISPLAY   # a bit extra safety
 
-[ -d "$SGE_ROOT" ] || unset SGE_ROOT
-
-##
-## System start scripts typically run as root user,
-## downgrade to a non-root user account. Adjust as needed
-##
-runas_user=nobody
-# -------------------------------------------------------------------------
-# this script should run as 'runas_user'
+#---------------------------------------------------------------------------
+# The following lines provide the necessary info for adding a startup script
+# according to the Linux Standard Base Specification (LSB).
 #
-if [ "$UID" -eq 0 -a "${runas_user:=root}" != root ]
+### BEGIN INIT INFO
+# Provides:       xmlqstat.httpi
+# Required-Start: $network $remote_fs
+# Should-Start:   network-remotefs
+# Required-Stop:
+# Default-Start:  3 5
+# Default-Stop: 0 1 2 6
+# Description:  start httpi for extra xmlqstat support
+### END INIT INFO
+#---------------------------------------------------------------------------
+
+# this script should run as 'runAs'
+if [ "$UID" -eq 0 -a "${runAs:=root}" != root ]
 then
-    exec sudo -S -u $runas_user $0 $@
+    exec sudo -S -u $runAs $0 $@
     exitcode=$?       # retain exitcode
 
     [ "$exitcode" == 0 ] || {
-       echo "could not change to $runas_user"
-       exit $exitcode
+        echo "could not change to $runAs"
+        exit $exitcode
     }
 fi
 
@@ -61,13 +72,14 @@ start)
     ;;
 
 stop)
-    echo "Stopping $desc: $name"
+    echo -n "Stopping $desc: "
     # get pid
-    pid=`ps aux | grep dhttpi | awk '{if (/dhhtpi:/) print $2}'`
+    pid=`ps aux | awk '{if (/dhttpi:/ && !/awk/) print $2}'`
     if [ -z "$pid" ]
     then
         echo "process not found"
     else
+        echo "sending TERM signal"
         kill -15 $pid
     fi
     ;;
@@ -83,5 +95,6 @@ restart)
     exit 1
     ;;
 esac
+
 exit 0
-# ------------------------------------------------------------- end-of-file
+# -------------------------------------------------------------- end-of-file
diff --git a/scripts/init-scripts/xmlqstat-cacher b/scripts/init-scripts/xmlqstat-cacher
--- a/scripts/init-scripts/xmlqstat-cacher
+++ b/scripts/init-scripts/xmlqstat-cacher
@@ -1,43 +1,60 @@
 #!/bin/sh
+# Simple start/stop script for the perl daemon that caches
+# GridEngine XML status data for the "xml-qstat" web application
 
-## Simple start/stop script for the perl daemon that caches
-## Grid Engine XML status data for the "xml-qstat" web application
-
-## CUSTOMIZE AS NEEDED
-: ${SGE_ROOT:=/opt/grid}
-: ${SGE_CELL:=default}
-
-CACHE_SGE_XML_HOME=/opt/xml-qstat/scripts
-
-export SGE_ROOT SGE_CELL CACHE_SGE_XML_HOME
-
-##
-## System start scripts typically run as root user,
-## downgrade to a non-root user account. Adjust as needed
-##
-runas_user=cfdadmin
-# -----------------------------------------------------------------------------
-# this script should run as 'runas_user'
+# 0. Define safe path
+PATH=/bin:/usr/bin
 #
-if [ "$UID" -eq 0 -a "${runas_user:=root}" != root ]
+## CUSTOMIZE AS NEEDED
+#
+# 1. Downgrade to a non-root user account (adjust as required)
+runAs=cfdadmin
+
+# 2. Location of the script
+CACHER_HOME=/opt/xml-qstat/scripts
+
+# 3. Require GridEngine for later queries
+SGE_ROOT=/opt/grid
+SGE_CELL=default
+
+#---------------------------------------------------------------------------
+# The following lines provide the necessary info for adding a startup script
+# according to the Linux Standard Base Specification (LSB).
+#
+### BEGIN INIT INFO
+# Provides:       xmlqstat.cacher
+# Required-Start: $network $remote_fs
+# Should-Start:   network-remotefs
+# Required-Stop:
+# Default-Start:  3 5
+# Default-Stop: 0 1 2 6
+# Description:  start xmlqstat cacher
+### END INIT INFO
+#---------------------------------------------------------------------------
+
+# this script should run as 'runAs'
+if [ "$UID" -eq 0 -a "${runAs:=root}" != root ]
 then
-    exec sudo -S -u $runas_user $0 $@
+    exec sudo -S -u $runAs $0 $@
     exitcode=$?       # retain exitcode
 
     [ "$exitcode" == 0 ] || {
-        echo "could not change to $runas_user"
+        echo "could not change to $runAs"
         exit $exitcode
     }
 fi
 
-## Init the Grid Engine path/environment variables
-## so our script can access Grid Engine commands
+# Init GridEngine path/environment variables
 if [ -f $SGE_ROOT/$SGE_CELL/common/settings.sh ]
 then
+    export SGE_ROOT SGE_CELL
     . $SGE_ROOT/$SGE_CELL/common/settings.sh
+else
+    unset SGE_ROOT SGE_CELL
 fi
 
-daemon=$CACHE_SGE_XML_HOME/xmlqstat-cacher.pl
+
+daemon=$CACHER_HOME/xmlqstat-cacher.pl
 name=xmlqstat-cacher
 desc="GridEngine XML Status Caching Daemon"
 
@@ -59,11 +76,18 @@ stop)
     echo "$name"
     ;;
 
+
+restart)
+    ## Stop (if running) and start anew
+    $0 stop
+    $0 start
+    ;;
+
 *)
-    echo "Usage: $0 {start|stop}" >&2
+    echo "Usage: $0 {start|stop|restart}" >&2
     exit 1
     ;;
 esac
 
 exit 0
-# ------------------------------------------------------------- end-of-file
+# -------------------------------------------------------------- end-of-file
