cleanup and modified init-scripts
- added simple 'stop' and 'restart' to init-scripts
- remove Changelog (since it wasn't really maintained anyhow)
- added TODO for taking notes
- remove retired/ directory (easy enough to get back in git)

diff --git a/scripts/init-scripts/cocoon b/scripts/init-scripts/cocoon
--- a/scripts/init-scripts/cocoon
+++ b/scripts/init-scripts/cocoon
@@ -1,7 +1,7 @@
 #!/bin/sh
-
-## Simple start script for the Cocoon server engine
-
+#
+# Simple start script for the Cocoon server engine
+#
 ## CUSTOMIZE AS REQUIRED
 #
 # require GridEngine information for later queries
@@ -19,6 +19,8 @@ export SGE_ROOT SGE_CELL JAVA_HOME COCOON_HOME
 if [ -f $SGE_ROOT/$SGE_CELL/common/settings.sh ]
 then
     . $SGE_ROOT/$SGE_CELL/common/settings.sh
+else
+    unset SGE_ROOT SGE_CELL
 fi
 
 # extra path for anything we wish to use via the java CommandGenerator
@@ -68,12 +70,25 @@ start)
     ;;
 
 stop)
-    echo "Usage: $0 {start}" >&2
-    exit 1
+    echo "Stopping $desc: $name"
+    # get pid
+    pid=`ps -f -C java | awk '{if (/cocoon/) print $2}'`
+    if [ -z "$pid" ]
+    then
+        echo "process not found"
+    else
+        kill -15 $pid
+    fi
+    ;;
+
+restart)
+    ## Stop (if running) and start anew
+    $0 stop
+    $0 start
     ;;
 
 *)
-    echo "Usage: $0 {start}" >&2
+    echo "Usage: $0 {start|stop|restart}" >&2
     exit 1
     ;;
 esac
diff --git a/scripts/init-scripts/httpi b/scripts/init-scripts/httpi
--- a/scripts/init-scripts/httpi
+++ b/scripts/init-scripts/httpi
@@ -1,10 +1,10 @@
 #!/bin/sh
-
-## Simple start script for the httpi web-server
-
+#
+# Simple start script for the httpi web-server
+#
 ## CUSTOMIZE AS REQUIRED
 #
-# require GridEngine information for later queries
+# maybe require GridEngine information for later queries
 : ${SGE_ROOT:=/opt/grid}
 
 HTTPI_HOME=/data/app/httpi
@@ -15,7 +15,9 @@ PATH=/bin:/usr/bin:$SGE_ROOT/bin/`$SGE_ROOT/util/arch`
 PATH=$PATH:/data/app/bin
 
 export SGE_ROOT PATH
-unset DISPLAY  # a bit extra safety
+unset DISPLAY   # a bit extra safety
+
+[ -d "$SGE_ROOT" ] || unset SGE_ROOT
 
 ##
 ## System start scripts typically run as root user,
@@ -59,12 +61,25 @@ start)
     ;;
 
 stop)
-    echo "Usage: $0 {start}" >&2
-    exit 1
+    echo "Stopping $desc: $name"
+    # get pid
+    pid=`ps aux | grep dhttpi | awk '{if (/dhhtpi:/) print $2}'`
+    if [ -z "$pid" ]
+    then
+        echo "process not found"
+    else
+        kill -15 $pid
+    fi
+    ;;
+
+restart)
+    ## Stop (if running) and start anew
+    $0 stop
+    $0 start
     ;;
 
 *)
-    echo "Usage: $0 {start}" >&2
+    echo "Usage: $0 {start|stop|restart}" >&2
     exit 1
     ;;
 esac
