reworked to handle multiple clusters
- interface with command-generator (single cluster only)
    /xmlqstat/qstat-jobs.html
    /xmlqstat/qstat-full.html
    /xmlqstat/qstat-terse.html
    /xmlqstat/job-{number}.html

- interface with file caching, works with qlicserver cached output
    /xmlqstat/cluster
        -> list available clusters
    /xmlqstat/cluster/{name}
        -> list xml cache files
    /xmlqstat/cluster/{name}/jobs
    /xmlqstat/cluster/{name}/jobinfo
    /xmlqstat/cluster/{name}/queues?(summary|warn)
    /xmlqstat/cluster/{name}/resources

- list config files
    /xmlqstat/config

diff --git a/scripts/init-scripts/cocoon b/scripts/init-scripts/cocoon
--- a/scripts/init-scripts/cocoon
+++ b/scripts/init-scripts/cocoon
@@ -5,16 +5,25 @@
 ## CUSTOMIZE AS REQUIRED
 #
 # require GridEngine information for later queries
-: ${SGE_ROOT:=/opt/n1ge6}
+# (only required when using the command-generator)
+: ${SGE_ROOT:=/opt/grid}
+: ${SGE_CELL:=default}
 
 JAVA_HOME=/usr/lib/jvm/java
 COCOON_HOME=/data/app/cocoon
-PATH=/bin:/usr/bin:$SGE_ROOT/bin/`$SGE_ROOT/util/arch`
+
+export SGE_ROOT SGE_CELL JAVA_HOME COCOON_HOME
+
+## Init the Grid Engine path/environment variables
+## so our script can access Grid Engine commands
+if [ -f $SGE_ROOT/$SGE_CELL/common/settings.sh ]
+then
+    . $SGE_ROOT/$SGE_CELL/common/settings.sh
+fi
 
 # extra path for anything we wish to use via the java CommandGenerator
 PATH=$PATH:/data/app/bin
 
-export SGE_ROOT JAVA_HOME COCOON_HOME PATH
 unset DISPLAY  # a bit extra safety
 
 ##
@@ -27,13 +36,13 @@ runas_user=cfdadmin
 #
 if [ "$UID" -eq 0 -a "${runas_user:=root}" != root ]
 then
-   exec sudo -S -u $runas_user $0 $@
-   exitcode=$?       # retain exitcode
+    exec sudo -S -u $runas_user $0 $@
+    exitcode=$?       # retain exitcode
 
-   [ "$exitcode" == 0 ] || {
-      echo "could not change to $runas_user"
-      exit $exitcode
-   }
+    [ "$exitcode" == 0 ] || {
+       echo "could not change to $runas_user"
+       exit $exitcode
+    }
 fi
 
 daemon=$COCOON_HOME/cocoon.sh
@@ -45,28 +54,28 @@ LOG=/var/log/cocoon
 LOG=/dev/null
 
 [ -f $daemon -a -x $daemon ] || {
-   echo "$daemon not found"
-   exit 5      # LSB compliant exit status - program is not installed
+    echo "$daemon not found"
+    exit 5      # LSB compliant exit status - program is not installed
 }
 
 test -f $daemon || exit 0
 set -e
 case "$1" in
 start)
-   echo -n "Starting $desc: "
-   $daemon servlet >> $LOG 2>&1 &
-   echo "$name"
-   ;;
+    echo -n "Starting $desc: "
+    $daemon servlet >> $LOG 2>&1 &
+    echo "$name"
+    ;;
 
 stop)
-   echo "Usage: $0 {start}" >&2
-   exit 1
-   ;;
+    echo "Usage: $0 {start}" >&2
+    exit 1
+    ;;
 
 *)
-   echo "Usage: $0 {start}" >&2
-   exit 1
-   ;;
+    echo "Usage: $0 {start}" >&2
+    exit 1
+    ;;
 esac
 exit 0
 # ------------------------------------------------------------- end-of-file
diff --git a/scripts/init-scripts/httpi b/scripts/init-scripts/httpi
--- a/scripts/init-scripts/httpi
+++ b/scripts/init-scripts/httpi
@@ -5,7 +5,7 @@
 ## CUSTOMIZE AS REQUIRED
 #
 # require GridEngine information for later queries
-: ${SGE_ROOT:=/opt/n1ge6}
+: ${SGE_ROOT:=/opt/grid}
 
 HTTPI_HOME=/data/app/httpi
 PATH=/bin:/usr/bin:$SGE_ROOT/bin/`$SGE_ROOT/util/arch`
@@ -27,13 +27,13 @@ runas_user=nobody
 #
 if [ "$UID" -eq 0 -a "${runas_user:=root}" != root ]
 then
-   exec sudo -S -u $runas_user $0 $@
-   exitcode=$?       # retain exitcode
+    exec sudo -S -u $runas_user $0 $@
+    exitcode=$?       # retain exitcode
 
-   [ "$exitcode" == 0 ] || {
-      echo "could not change to $runas_user"
-      exit $exitcode
-   }
+    [ "$exitcode" == 0 ] || {
+       echo "could not change to $runas_user"
+       exit $exitcode
+    }
 fi
 
 daemon=$HTTPI_HOME/httpi
@@ -45,28 +45,28 @@ LOG=/var/log/httpi
 LOG=/dev/null
 
 [ -f $daemon -a -x $daemon ] || {
-   echo "$daemon not found"
-   exit 5      # LSB compliant exit status - program is not installed
+    echo "$daemon not found"
+    exit 5      # LSB compliant exit status - program is not installed
 }
 
 test -f $daemon || exit 0
 set -e
 case "$1" in
 start)
-   echo -n "Starting $desc: "
-   $daemon >> $LOG 2>&1 &
-   echo "$name"
-   ;;
+    echo -n "Starting $desc: "
+    $daemon >> $LOG 2>&1 &
+    echo "$name"
+    ;;
 
 stop)
-   echo "Usage: $0 {start}" >&2
-   exit 1
-   ;;
+    echo "Usage: $0 {start}" >&2
+    exit 1
+    ;;
 
 *)
-   echo "Usage: $0 {start}" >&2
-   exit 1
-   ;;
+    echo "Usage: $0 {start}" >&2
+    exit 1
+    ;;
 esac
 exit 0
 # ------------------------------------------------------------- end-of-file
diff --git a/scripts/init-scripts/sge-xml-cacher b/scripts/init-scripts/sge-xml-cacher
--- a/scripts/init-scripts/sge-xml-cacher
+++ b/scripts/init-scripts/sge-xml-cacher
@@ -4,7 +4,7 @@
 ## Grid Engine XML status data for the "xml-qstat" web application
 
 ## CUSTOMIZE AS NEEDED
-: ${SGE_ROOT:=/opt/n1ge6}
+: ${SGE_ROOT:=/opt/grid}
 : ${SGE_CELL:=default}
 
 CACHE_SGE_XML_HOME=/opt/xml-qstat/scripts
@@ -34,7 +34,7 @@ fi
 ## so our script can access Grid Engine commands
 if [ -f $SGE_ROOT/$SGE_CELL/common/settings.sh ]
 then
-   . $SGE_ROOT/$SGE_CELL/common/settings.sh
+    . $SGE_ROOT/$SGE_CELL/common/settings.sh
 fi
 
 daemon=$CACHE_SGE_XML_HOME/sge-xml-cacher.pl
@@ -42,27 +42,28 @@ name=sge-xml-cacher
 desc="GridEngine XML Status Cache Daemon"
 
 [ -f $daemon -a -x $daemon ] || {
-   echo "$daemon not found"
-   exit 5      # LSB compliant exit status - program is not installed
+    echo "$daemon not found"
+    exit 5      # LSB compliant exit status - program is not installed
 }
 
 case "$1" in
 start)
-   echo -n "Starting $desc: "
-   $daemon -d
-   echo "$name"
-   ;;
+    echo -n "Starting $desc: "
+    $daemon -d
+    echo "$name"
+    ;;
 
 stop)
-   echo -n "Stopping $desc: "
-   $daemon -k
-   echo "$name"
-   ;;
+    echo -n "Stopping $desc: "
+    $daemon -k
+    echo "$name"
+    ;;
 
 *)
-   echo "Usage: $0 {start|stop}" >&2
-   exit 1
-   ;;
+    echo "Usage: $0 {start|stop}" >&2
+    exit 1
+    ;;
 esac
 
 exit 0
+# ------------------------------------------------------------- end-of-file
